-- @no-transaction
-- ============================================================
-- MIGRATION 028: Risk Cases — Phase-8.7 Security Ops Triage
-- ============================================================
--
-- Adds a human-in-the-loop triage layer on top of the
-- behavioral risk pipeline from Phases 8.5/8.6.
--
--   risk_cases
--     One OPEN case per (organization_id, user_id) at a time.
--     Created automatically by riskCase.worker when a user's
--     risk_level reaches HIGH or CRITICAL.
--     Workflow: OPEN → ACKNOWLEDGED → CLOSED (human-driven).
--     A new case is auto-created on the next worker cycle if
--     the user's risk spikes again after a previous case was
--     CLOSED.
--     Retention: cases are kept indefinitely as an audit trail.
--     Archive CLOSED cases older than 1 year via a future
--     archival migration; do NOT delete without operator sign-off.
--
--   behavioral_risk_events (ALTER)
--     Adds triage annotation columns (triage_status, triaged_by,
--     triage_note, triaged_at) and a back-reference to the case
--     (risk_case_id).  All new columns are NULL-safe and additive
--     — they do NOT affect the Phase-8.5/8.6 scoring pipeline.
--
-- Phase 1 — transactional DDL (BEGIN / COMMIT)
-- Phase 2 — CONCURRENTLY indexes (outside transaction)
-- ============================================================


-- ═══════════════════════════════════════════════════════════════════════════════
-- PHASE 1 — Transactional schema changes
-- ═══════════════════════════════════════════════════════════════════════════════

BEGIN;

-- ── risk_cases ────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS risk_cases (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id  UUID        NOT NULL,
  user_id          UUID        NOT NULL,

  -- ── Workflow status ─────────────────────────────────────────────────────────
  -- OPEN:         created by worker; awaiting operator action
  -- ACKNOWLEDGED: operator has seen the case (risk may still be active)
  -- CLOSED:       operator resolved the case; close_reason required
  status           VARCHAR(20) NOT NULL DEFAULT 'OPEN'
                     CHECK (status IN ('OPEN', 'ACKNOWLEDGED', 'CLOSED')),

  -- ── Live risk snapshot (refreshed every worker cycle while OPEN) ────────────
  -- risk_level allows NORMAL so the case reflects current posture even after
  -- the user's score decays below the trigger threshold.
  risk_score       INTEGER     NOT NULL,
  risk_level       VARCHAR(10) NOT NULL
                     CHECK (risk_level IN ('NORMAL', 'ELEVATED', 'HIGH', 'CRITICAL')),
  -- signals_summary clone from user_risk_state at last sync
  signals          JSONB       NOT NULL DEFAULT '{}',

  -- ── Peak snapshot since case opened (monotonically increasing) ─────────────
  -- Preserved even as current risk_score drops. Operators can see
  -- how severe the situation was at its worst.
  peak_risk_score  INTEGER     NOT NULL,
  peak_risk_level  VARCHAR(10) NOT NULL
                     CHECK (peak_risk_level IN ('ELEVATED', 'HIGH', 'CRITICAL')),

  -- ── Operator actions ────────────────────────────────────────────────────────
  acknowledged_by  UUID        NULL,  -- user.id of the operator who acknowledged
  acknowledged_at  TIMESTAMP   NULL,
  closed_by        UUID        NULL,  -- user.id of the operator who closed
  closed_at        TIMESTAMP   NULL,
  close_reason     TEXT        NULL,  -- required when closing; min 10 chars enforced in service

  -- ── Timestamps ──────────────────────────────────────────────────────────────
  opened_at        TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE risk_cases IS
  'Security operations triage cases generated by riskCase.worker (Phase-8.7). '
  'One OPEN case per user+org at a time (enforced by idx_rc_org_user_open). '
  'Closed cases are retained indefinitely for the audit trail. '
  'Archive cases older than 1 year via a dedicated archival job.';

COMMENT ON COLUMN risk_cases.risk_score IS
  'Current risk score — refreshed from user_risk_state each worker cycle. '
  'May decrease below trigger threshold while case remains OPEN.';

COMMENT ON COLUMN risk_cases.peak_risk_score IS
  'Highest risk_score recorded since case was opened. Monotonically increasing.';

COMMENT ON COLUMN risk_cases.peak_risk_level IS
  'Risk level corresponding to peak_risk_score. '
  'CHECK constraint excludes NORMAL — cases are only created for ELEVATED+ users.';

COMMENT ON COLUMN risk_cases.signals IS
  'JSONB clone of user_risk_state.signals_summary at last sync. '
  'Structure: { "SIGNAL_TYPE": { "score": N, "events": N }, ... }';

COMMENT ON COLUMN risk_cases.close_reason IS
  'Operator-provided explanation for closing the case. '
  'Minimum 10 characters enforced by the service layer, not the DB.';

-- ── behavioral_risk_events extensions ─────────────────────────────────────────
-- All columns are additive. Phase-8.5/8.6 scoring logic is unaffected.

ALTER TABLE behavioral_risk_events
  -- Back-reference to the triage case. NULL until riskCase.worker links it.
  ADD COLUMN IF NOT EXISTS risk_case_id   UUID        NULL,

  -- Operator triage verdict for this individual event.
  -- UNREVIEWED: default — event has not been assessed by an operator.
  -- BENIGN:     operator determined the activity is expected / non-threatening.
  -- SUSPICIOUS: operator flagged the activity as worthy of escalation.
  ADD COLUMN IF NOT EXISTS triage_status  VARCHAR(20) NOT NULL DEFAULT 'UNREVIEWED'
    CHECK (triage_status IN ('UNREVIEWED', 'BENIGN', 'SUSPICIOUS')),

  ADD COLUMN IF NOT EXISTS triaged_by     UUID        NULL,   -- user.id of operator
  ADD COLUMN IF NOT EXISTS triage_note    TEXT        NULL,   -- optional operator note
  ADD COLUMN IF NOT EXISTS triaged_at     TIMESTAMP   NULL;   -- when triage was recorded

COMMENT ON COLUMN behavioral_risk_events.risk_case_id IS
  'FK to risk_cases.id. Set by riskCase.worker bulk-link step. '
  'NULL for events not yet assigned to a case (pre-worker or decayed cases).';

COMMENT ON COLUMN behavioral_risk_events.triage_status IS
  'Operator assessment of this individual risk event. '
  'UNREVIEWED (default) → BENIGN or SUSPICIOUS via POST /risk-events/:id/triage.';

COMMIT;


-- ═══════════════════════════════════════════════════════════════════════════════
-- PHASE 2 — CONCURRENTLY indexes
--
-- All must run OUTSIDE a transaction block. IF NOT EXISTS guards re-runs.
-- Rationale for each index is documented inline.
-- ═══════════════════════════════════════════════════════════════════════════════

-- ── risk_cases indexes ────────────────────────────────────────────────────────

-- Enforces one OPEN case per (org, user). Partial index excludes CLOSED and
-- ACKNOWLEDGED rows so historical cases do not block new OPEN cases.
-- Required for ON CONFLICT (organization_id, user_id) WHERE status = 'OPEN'
-- inference in the worker's INSERT ... ON CONFLICT upsert.
CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS idx_rc_org_user_open
  ON risk_cases (organization_id, user_id)
  WHERE status = 'OPEN';

-- Covers the admin dashboard list query:
--   WHERE organization_id = $1 AND status = $2  ORDER BY opened_at DESC
-- Partial: excludes CLOSED cases from the hot path — closed cases are
-- fetched less frequently and don't need a dedicated covering index.
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_rc_org_status_open
  ON risk_cases (organization_id, opened_at DESC)
  WHERE status IN ('OPEN', 'ACKNOWLEDGED');

-- Full-status index for historical / audit queries that include CLOSED cases.
-- Separate from idx_rc_org_status_open to keep the hot-path index tight.
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_rc_org_status_all
  ON risk_cases (organization_id, status, opened_at DESC);

-- ── behavioral_risk_events extensions ─────────────────────────────────────────

-- Covers case detail query:
--   WHERE risk_case_id = $1 AND organization_id = $2  ORDER BY detected_at DESC
-- Partial: NULL risk_case_id rows are unlinked events — excluded to keep the
-- index small (unlinked events are the majority during early operation).
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_bre_risk_case_id
  ON behavioral_risk_events (risk_case_id, organization_id)
  WHERE risk_case_id IS NOT NULL;

-- Covers operator triage workqueue query:
--   WHERE organization_id = $1 AND triage_status = 'UNREVIEWED'
-- Partial: only indexes UNREVIEWED rows — the rows operators need to act on.
-- As events are triaged (→ BENIGN or SUSPICIOUS) they drop out of the index,
-- keeping it compact over time.
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_bre_triage_unreviewed
  ON behavioral_risk_events (organization_id, user_id, detected_at DESC)
  WHERE triage_status = 'UNREVIEWED';
